name: Build Project
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    uses: github-actions/github-actions/.github/workflows/build-dotnet-workflow.yml@main
    with:
      SOLUTION_PATH: ${{ vars.SOLUTION_PATH }}
      OUTPUT_FILENAME: ${{ vars.OUTPUT_FILENAME }}
