# This is a basic workflow to help you get started with Actions
name: docker build and push

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# done use this directlt
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          username: ${{ env.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_PASSWORD }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ vars.DOCKER_FILE_PATH }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dockerfordotnetapi:latest, ${{ secrets.DOCKERHUB_USERNAME }}/dockerfordotnetapi:${{ github.run_number }}
