name: Build Project
 
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  build:
    #uses: SankumSan/github-actions/.github/workflows/build-dotnet-workflow.yml@main
    #uses: SankumSan/github-actions/.github/workflows/build-mul-os-workflow.yml@main
    uses: SankumSan/github-actions/.github/workflows/build-push-docker-workflow.yml@main
    with:
      SOLUTION_PATH: ${{ vars.SOLUTION_PATH }}
      OUTPUT_FILENAME: ${{ vars.OUTPUT_FILENAME }}
      DOCKER_FILE_PATH: ${{ vars.DOCKER_FILE_PATH }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
